name: Polls and GCB Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '13 */2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: python polls.py
        env:
          SENDER: ${{secrets.SENDER}}
          PASSWORD: ${{secrets.PASSWORD}}
          RECIPIENT: ${{secrets.RECIPIENT}}
      - run: python fte.py
        env:
          SENDER: ${{secrets.SENDER}}
          PASSWORD: ${{secrets.PASSWORD}}
          RECIPIENT: ${{secrets.RECIPIENT}}
      - name: Commit and push if changed
        run: |-
          git config user.name "Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
