name: Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: python task.py
        env:
          SENDER: ${{secrets.SENDER}}
          RECIPIENT: ${{secrets.RECIPIENT}}
          PASSWORD: ${{secrets.PASSWORD}}
          NAME: ${{secrets.NAME}}
          BIRTH_MONTH_AND_YEAR: ${{secrets.BIRTH_MONTH_AND_YEAR}}
          ZIP: ${{secrets.ZIP}}
