name: Voter Status Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '45 6 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: python task.py
        env:
          NAME: ${{secrets.NAME}}
          BIRTH_MONTH_AND_YEAR: ${{secrets.BIRTH_MONTH_AND_YEAR}}
          ZIP: ${{secrets.ZIP}}
      - name: Commit and push if changed
        run: |-
          git config user.name "Actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Voter Status Change" || exit 0
          git push
